language: csharp
mono: 4.6.2
env:
  global:
    - homegenie_version: 1.1-rc1.527
    - secure: not_set
solution: HomeGenie_Linux/HomeGenie_Linux.sln
before_install:
before_script:
script:
  - xbuild /p:Configuration=Debug HomeGenie_Linux/HomeGenie_Linux.sln
after_success:
  - HomeGenie_Linux/Packager/builddeb.sh
after_failure:
deploy:
  provider: releases
  api_key:
    secure: '$(github_deploy_key)'
  file:
    - "HomeGenie_Linux/Packager/Output/homegenie_$(homegenie_version)_all.deb"
    - "HomeGenie_Linux/Packager/Output/homegenie_$(homegenie_version).tgz"
  skip_cleanup: true
  on:
    tags: true

