version: 1.0.{build}
branches:
  except:
  - gh-pages
image: Visual Studio 2015
configuration: Debug
before_build:
  - nuget restore -PackagesDirectory .\HomeGenie.Tests
build:
  project: .\HomeGenie_Windows\HomeGenie_VS10.sln
  verbosity: minimal
after_build:
- cmd: >-
    echo "Bundling installer for HomeGenie %APPVEYOR_REPO_TAG_NAME%"
    
    dir "HomeGenie\bin\Debug"

    cd "HomeGenie_Windows\Packager\"

    "C:\Program Files (x86)\Inno Setup 5\iscc.exe" /Q /F"HomeGenie_%APPVEYOR_REPO_TAG_NAME%" setup.iss

    echo "Adding artifact"

    echo "TODO: should rename mysetup as homegenie_%APPVEYOR_REPO_TAG_NAME%.exe"

    appveyor PushArtifact "Output\HomeGenie_%APPVEYOR_REPO_TAG_NAME%.exe"

test:
  assemblies:
    only:
      - HomeGenie.Tests/bin/Debug/HomeGenie.Tests.dll
deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: 'HomeGenie $(APPVEYOR_REPO_TAG_NAME)'
  provider: GitHub
  auth_token:
    secure:  1aMBEFi1qBAoV4H+LYx7hoVLgXJfndGoQ8I8qjLsoxXNA1zS+zgQHi2zVlRrmw1v
  artifact: 'Output\HomeGenie_$(APPVEYOR_REPO_TAG_NAME).exe'
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only

