version: 1.0.{build}
branches:
  except:
    - gh-pages
image: Visual Studio 2015
configuration: Debug
environment:
  homegenie_version: 1.1-rc1.527
build:
  project: .\HomeGenie_Windows\HomeGenie_VS10.sln
  verbosity: minimal
after_build:
- cmd: >-
    echo "Bundling installer for HomeGenie %homegenie_version%"
    
    dir "HomeGenie\bin\Debug"

    cd "HomeGenie_Windows\Packager\"

    "C:\Program Files (x86)\Inno Setup 5\iscc.exe" /Q /F"HomeGenie_%homegenie_version%" setup.iss

    echo "Adding artifact"

    echo "TODO: should rename mysetup as homegenie_%homegenie_version%.exe"

    appveyor PushArtifact "Output\HomeGenie_%homegenie_version%.exe"

deploy:
  release: v$(homegenie_version)
  description: 'HomeGenie v$(homegenie_version)'
  provider: GitHub
  auth_token:
    secure:  '$(github_deploy_key)'
  artifact: 'Output\HomeGenie_$(homegenie_version).exe'
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only

